"""Shared dark-matter normalization and ontology helpers."""

from .candidate_ontology import (
    AMBIGUOUS_REQUIRES_DM_NEARBY,
    CANDIDATE_TAGS,
    COMPILED,
    DM_TAGS_INFO,
    NEAR_DM,
    PATTERNS,
    SPECIES_LABEL_MAP,
    candidate_species_labels,
    categorize_arxiv,
    dm_nearby_in_window,
    expand_dm_tags,
    extract_dm_tags_with_spans,
    filter_candidate_tags,
    normalize_text,
    primary_arxiv_class,
)
from .normalization import (
    MAX_CTX_WORDS,
    MAX_DM_PER_CTX,
    MAX_MATH_TOKENS_PER_CTX,
    MIN_CENTER_SENT_WORDS,
    MIN_CTX_WORDS,
    SAFE_ABBREV_EXPANSIONS,
    SECONDARY_PHYSICS_EXPANSIONS,
    SOFT_CTX_WORDS,
    TARGET,
    canon_dm,
    iter_sentences_norm,
    normalize_segment,
    pat,
)
from .tfidf_preproc import TOK_PAT, preproc, tokenize_preproc_text

__all__ = [
    "TARGET",
    "pat",
    "MAX_CTX_WORDS",
    "MIN_CTX_WORDS",
    "MIN_CENTER_SENT_WORDS",
    "SOFT_CTX_WORDS",
    "MAX_DM_PER_CTX",
    "MAX_MATH_TOKENS_PER_CTX",
    "SAFE_ABBREV_EXPANSIONS",
    "SECONDARY_PHYSICS_EXPANSIONS",
    "canon_dm",
    "normalize_segment",
    "iter_sentences_norm",
    "normalize_text",
    "PATTERNS",
    "AMBIGUOUS_REQUIRES_DM_NEARBY",
    "NEAR_DM",
    "COMPILED",
    "extract_dm_tags_with_spans",
    "DM_TAGS_INFO",
    "CANDIDATE_TAGS",
    "SPECIES_LABEL_MAP",
    "expand_dm_tags",
    "filter_candidate_tags",
    "candidate_species_labels",
    "primary_arxiv_class",
    "categorize_arxiv",
    "dm_nearby_in_window",
    "TOK_PAT",
    "preproc",
    "tokenize_preproc_text",
]
